  version: '3.8'

  services:
    backend:
      build:
        context: .
        dockerfile: dockerfile
      container_name: go-backend
      environment:
        DATABASE_URL: postgres://postgres:Dev@dgp21@db:5432/jobportal?sslmode=disable
      ports:
        - "8082:8081"
      depends_on:
        - db

    frontend:
      build:
        context: .
        dockerfile: dockerfile.frontend
      container_name: js-frontend
      ports:
        - "3004:80"

    db:
      image: postgres:14
      container_name: postgres-db
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Dev@dgp21
        POSTGRES_DB: jobportal
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5433:5432"

  volumes:
    postgres_data:
